### ISSUE TITLE
Inject data on-demand in Influx

### ISSUE THREAD

**Issue by lribiere** [Aura-healthcare/Aura_infrastructure#8]
Ecrire un script (python, bash, ...) permettant d'injecter à la demander des données dans la base influx.

S'appuyer des fonctions définies dans ce module python : https://github.com/Aura-healthcare/data_ingestor_and_features_creator/blob/master/influxdb_raw_data_injector/influxdb_raw_data_injector.py

**Comment by RGirard94** [comment]
**Problème** : Les fichiers semblent être lus, mais aucune donnée n'est fournit à la base influx.

**Comment by RGirard94** [comment]
Le script fonctionne avec les versions de pandas, numpy et influx spécifiées dans le fichier requirement.txt
