### ISSUE TITLE
Generate test data files for ingestion

### ISSUE THREAD

**Issue by lribiere** [Aura-healthcare/Aura_infrastructure#9]
Two types of test files are needed : RRInterval and Accel/Gyro files.

For RRInterval, the json scheme to follow is the following :
{
  "user": "f29dd72d-357d-45c7-bde3-3848350b4b1a",
  "type": "RrInterval",
  "device_address": "7B-1B-7F-E5-F2-4A",
  "data": [
    "2018-10-04T16:17:02.890 454",
    "2018-10-04T16:17:02.890 449",
    "2018-10-04T16:17:03.856 446",
    "2018-10-04T16:17:03.856 445",
    "2018-10-04T16:17:04.890 444"
    ...
    ]
}
The RR values (after the date for each "data" table entry) should be somewhat different from one line to the next and should lie between the range : [300, 2000]. The data table could contain 1 million values to start.

For Accel/Gyro, the json scheme to follow is the following :
{
  "user": "f29dd72d-357d-45c7-bde3-3848350b4b1a",
  "type": "MotionAccelerometer",
  "device_address": "7B-1B-7F-E5-F2-4A",
  "data": [
    "2018-10-04T19:21:40.163 -0.22583008 0.88635254 -0.46899414 2G",
    "2018-10-04T19:21:40.212 -0.2244873 0.8843994 -0.47027588 2G",
    "2018-10-04T19:21:40.262 -0.22381592 0.885437 -0.4711914 2G",
    "2018-10-04T19:21:40.265 -0.22644043 0.8858032 -0.4710083 2G",
    "2018-10-04T19:21:40.268 -0.22644043 0.8858032 -0.4710083 2G",
    ...
    ]
}

The 3 values (after the date for each "data" table entry) should be somewhat different from one line to the next and should lie between the range : [-1, 1]. The data table could contain 1 million values to start.

**Comment by RGirard94** [comment]
Script terminé. En attente de vérification.
